### ISSUE TITLE
使用-o 命令后没有产生.ics文件，而是直接在终端打印

### ISSUE THREAD

**Issue by leo-ashton** [qwqVictor/CQUPT-ics#1]
当我使用命令```python cli.py -o cqupt.ics <我的学号>```时，在目录下并没有生成对应的.ics文件，而是直接在终端上打印出了文件的内容
![image](https://user-images.githubusercontent.com/60648876/154063021-cfe1f210-6866-4b70-912b-f95cf96f051a.png)

**Comment by junyilou** [comment]
经查，在 [cli.py](https://github.com/qwqVictor/CQUPT-ics/blob/main/cli.py) 中 open 没有指定打开方式，若文件不存在将导致写入失败，已在新 [commit](https://github.com/qwqVictor/CQUPT-ics/commit/8a2b8c8261148a9d76d98d8fce7fbc32a94f74b5) 修复此问题。

**Comment by leo-ashton** [comment]
> 经查，在 [cli.py](https://github.com/qwqVictor/CQUPT-ics/blob/main/cli.py) 中 open 没有指定打开方式，若文件不存在将导致写入失败，已在新 [commit](https://github.com/qwqVictor/CQUPT-ics/commit/8a2b8c8261148a9d76d98d8fce7fbc32a94f74b5) 修复此问题。

现在可以了，不过用该命令生成的 ics 文件使用 Win10 自带的日历导入显示文件已损坏，指定 provider 为 jwzxdirect 后，可以导入但是标题为乱码，且日期不正确，ics 文件的 TZID 字段似乎有问题。手动指定 start-day 后日期正确但标题仍为乱码。
![image](https://user-images.githubusercontent.com/60648876/154213908-d9db3cd9-9159-4687-825c-3c4bf2c50489.png)

**Comment by junyilou** [comment]
> > 经查，在 [cli.py](https://github.com/qwqVictor/CQUPT-ics/blob/main/cli.py) 中 open 没有指定打开方式，若文件不存在将导致写入失败，已在新 [commit](https://github.com/qwqVictor/CQUPT-ics/commit/8a2b8c8261148a9d76d98d8fce7fbc32a94f74b5) 修复此问题。
> 
> 现在可以了，不过用该命令生成的 ics 文件使用 Win10 自带的日历导入显示文件已损坏，指定 provider 为 jwzxdirect 后，可以导入但是标题为乱码，且日期不正确，ics 文件的 TZID 字段似乎有问题。手动指定 start-day 后日期正确但标题仍为乱码。 ![image](https://user-images.githubusercontent.com/60648876/154213908-d9db3cd9-9159-4687-825c-3c4bf2c50489.png)

由于目前在寒假期间，三个数据源的服务情况如下：
* 默认数据源（红岩网校的掌上重邮 app）：没有在工作，请求课表直接返回文字 Service Unavailable，由于代码中并没有设置在一个数据源错误时自动换另一个，现在使用默认数据源则会出错（但应该会在运行中直接报 HTTP 503）
* We重邮：可以正常查到课表，但刚刚验证的情况是 We重邮 似乎修改了查课表的机制，现在要求查课表的的时候要同时提交正确的学生绑定微信的 Open ID 才可以返回课表（如果您不熟悉 Open ID，可以简单理解为每个微信用户和每个小程序有一个固定的 token），代码中由于不知道每个学生不同的 token 所以直接打了 None，这在之前是可以工作的（证明 We重邮 服务器之前并不校验这一信息）。因此目前来看 We重邮 数据源可以说是已经无法很简单的工作了
* 教务在线：日期错误是因为当前教务在线课表页面显示「目前是第 0 周」，这也是目前在假期会出现的临时问题，关于乱码问题将在稍后给您回复

**Comment by junyilou** [comment]
<img width="960" alt="outlook-window" src="https://user-images.githubusercontent.com/15688661/154393578-630768a7-3601-45c5-90eb-ab3ae38d34b5.png">

验证了最新版本的 Microsoft 365 Outlook 软件可以不改任何设置的情况下直接打开并正确显示文件，遇到乱码通常是编码问题，您可以尝试搜索「Outlook 编码错误」等问题的解决方案，检查有没有关于 Unicode 或 UTF-8 的设置错误再试

用到的文件下载（由于 GitHub 不支持上传 ics，改后缀名为 ics 后使用）[cqupt.ics.txt](https://github.com/qwqVictor/CQUPT-ics/files/8085098/cqupt.ics.txt)

**Comment by leo-ashton** [comment]
> <img alt="outlook-window" width="960" src="https://user-images.githubusercontent.com/15688661/154393578-630768a7-3601-45c5-90eb-ab3ae38d34b5.png">
> 
> 验证了最新版本的 Microsoft 365 Outlook 软件可以不改任何设置的情况下直接打开并正确显示文件，遇到乱码通常是编码问题，您可以尝试搜索「Outlook 编码错误」等问题的解决方案，检查有没有关于 Unicode 或 UTF-8 的设置错误再试
> 
> 用到的文件下载（由于 GitHub 不支持上传 ics，改后缀名为 ics 后使用）[cqupt.ics.txt](https://github.com/qwqVictor/CQUPT-ics/files/8085098/cqupt.ics.txt)

好的，我在转换文件编码为 UTF-8 后，可以用自带的日历应用导入了，谢谢~
