### ISSUE TITLE
请求添加开源许可协议

### ISSUE THREAD

**Issue by chz2012** [qwqVictor/CQUPT-ics#2]
作者您好，我在我的个人服务器上使用了这份代码，并分享给了几个同学，都表示非常方便。我希望在阅读完这些代码后，能够根据实际体验进行适当修改。故特此向您请求为这个项目添加一份开源许可协议，我对此表示衷心感谢。

**Comment by qwqVictor** [comment]
抱歉这个 issue 被淹没在一片邮件里面现在才看见。

License 我和 @junyilou 简单商量了一下决定采用 MIT，很快就会 commit 到仓库中，感谢支持。
